baseURL = 'https://motimoti-dev.web.app/'
languageCode = 'ja-ja'
title = 'ã‚‚ã¡æ—¥è¨˜'
theme = 'github-style'
googleAnalytics = ""
account = "motisan_info"

[params]
  author = "ã‚‚ã¡"
  description = "ã‚‚ã¡ã§ã™ï¼çµµã‚’æã„ãŸã‚Šã€å‹•ç”»ã‚’ä½œã£ãŸã‚Šã€Twitterã‚’ã—ãŸã‚Šã—ã¦æ—¥ã€…ã‚’éã”ã—ã¦ã„ã¾ã™ã€‚ã“ã®ãƒ–ãƒ­ã‚°ã¯ã‚¤ãƒ©ã‚¹ãƒˆä¾é ¼ã«é–¢ã™ã‚‹ã“ã¨ã‚„å€‹äººçš„ã«è¨€ã„ãŸã„ã“ã¨ã ã£ãŸã‚Šæ—¥ã€…ã®æ—¥è¨˜ã‚’æ›¸ã„ã¦ã„ã‚‹ã‚‚ã®ã§ã™ã€‚"
  github = "motimoti-dev"
  twitter = ""
  url = "https://github.com/motimoti-dev"
  rss = true
  lastmod = true
  location = "ã‚‚ã¡å›½"
  userStatusEmoji = "ğŸ¥¦"
  favicon = "/images/icon.png"

  [[params.links]]
    title = "Link"
    href = "https://motisan.info"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]